/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ForumCategory {
  'id' : Id,
  'postCount' : bigint,
  'name' : string,
  'description' : string,
}
export type Id = bigint;
export interface Post {
  'id' : Id,
  'body' : string,
  'author' : Principal,
  'timestamp' : Time,
  'threadId' : Id,
}
export interface Thread {
  'id' : Id,
  'categoryId' : Id,
  'upvotes' : bigint,
  'title' : string,
  'body' : string,
  'author' : Principal,
  'timestamp' : Time,
  'replyCount' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], ForumCategory>,
  'createPost' : ActorMethod<[Id, string], Post>,
  'createThread' : ActorMethod<[string, string, Id], Thread>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getThreadDetail' : ActorMethod<[Id], Thread>,
  'getThreadWithPosts' : ActorMethod<
    [Id],
    { 'thread' : Thread, 'posts' : Array<Post> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<ForumCategory>>,
  'listThreadsByCategory' : ActorMethod<[Id], Array<Thread>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'upvoteThread' : ActorMethod<[Id], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];