/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Id = IDL.Nat64;
export const ForumCategory = IDL.Record({
  'id' : Id,
  'postCount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : Id,
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'threadId' : Id,
});
export const Thread = IDL.Record({
  'id' : Id,
  'categoryId' : Id,
  'upvotes' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'replyCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [ForumCategory], []),
  'createPost' : IDL.Func([Id, IDL.Text], [Post], []),
  'createThread' : IDL.Func([IDL.Text, IDL.Text, Id], [Thread], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getThreadDetail' : IDL.Func([Id], [Thread], ['query']),
  'getThreadWithPosts' : IDL.Func(
      [Id],
      [IDL.Record({ 'thread' : Thread, 'posts' : IDL.Vec(Post) })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(ForumCategory)], ['query']),
  'listThreadsByCategory' : IDL.Func([Id], [IDL.Vec(Thread)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'upvoteThread' : IDL.Func([Id], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Id = IDL.Nat64;
  const ForumCategory = IDL.Record({
    'id' : Id,
    'postCount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : Id,
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'threadId' : Id,
  });
  const Thread = IDL.Record({
    'id' : Id,
    'categoryId' : Id,
    'upvotes' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'replyCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [ForumCategory], []),
    'createPost' : IDL.Func([Id, IDL.Text], [Post], []),
    'createThread' : IDL.Func([IDL.Text, IDL.Text, Id], [Thread], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getThreadDetail' : IDL.Func([Id], [Thread], ['query']),
    'getThreadWithPosts' : IDL.Func(
        [Id],
        [IDL.Record({ 'thread' : Thread, 'posts' : IDL.Vec(Post) })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(ForumCategory)], ['query']),
    'listThreadsByCategory' : IDL.Func([Id], [IDL.Vec(Thread)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'upvoteThread' : IDL.Func([Id], [], []),
  });
};

export const init = ({ IDL }) => { return []; };